apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: memo-app
type: Opaque
data:
  mongo-root-username: bWVtb19hZG1pbg==
  mongo-root-password: bWVtb19wYXNzd29yZDEyMw==
  mongo-database: bWVtby1hcHAtZGI=
