apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-app-frontend
  namespace: memo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memo-app-frontend
  template:
    metadata:
      labels:
        app: memo-app-frontend
    spec:
      containers:
        - name: memo-app-frontend
          image: imumesh/memo-app-frontend:master-2025-11-23
          ports:
            - containerPort: 8080  
          