apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: memo-app
type: Opaque
data:
  database-url: bW9uZ29kYjovL21lbW9fYWRtaW46bWVtb19wYXNzd29yZDEyM0Btb25nb2RiOjI3MDE3L21lbW8tYXBwLWRiP2F1dGhTb3VyY2U9YWRtaW4=
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl
  jwt-expires-in: OTBk
  jwt-cookie-expires: OTA=
